# Generated by Django 4.2 on 2023-05-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WantedPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("photo", models.URLField()),
                ("crimes_committed", models.TextField()),
                ("crime_type", models.TextField(default="Cyber", max_length=100)),
                ("investigation_status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Wanted Persons",
            },
        ),
    ]
