# Generated by Django 4.2 on 2023-09-29 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("idwall", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wantedperson",
            options={},
        ),
    ]
