# Generated by Django 4.2 on 2023-05-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idwall", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wantedperson",
            old_name="nationality",
            new_name="language",
        ),
        migrations.RemoveField(
            model_name="wantedperson",
            name="arrest_warrants",
        ),
        migrations.AlterField(
            model_name="wantedperson",
            name="crime_type",
            field=models.TextField(default="Cyber", max_length=100),
        ),
        migrations.AlterField(
            model_name="wantedperson",
            name="investigation_status",
            field=models.BooleanField(default=True),
        ),
    ]
