# Generated by Django 4.2 on 2023-05-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idwall", "0002_rename_nationality_wantedperson_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wantedperson",
            name="language",
            field=models.CharField(default="n/a", max_length=50),
        ),
        migrations.AlterField(
            model_name="wantedperson",
            name="physical_description",
            field=models.TextField(default="n/a"),
        ),
    ]
